# Generated by Django 4.0.4 on 2022-08-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_middlename_reg_areyou_reg_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='venuedetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
