# Generated by Django 4.0.4 on 2022-08-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_photographerdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='conformpassword',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
