# Generated by Django 4.0.4 on 2022-08-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_reg_conformpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='beautisiondetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_image', models.ImageField(upload_to='media/')),
                ('b_name', models.CharField(max_length=50)),
                ('b_city', models.CharField(max_length=50)),
                ('b_price', models.IntegerField()),
            ],
        ),
    ]
