# Generated by Django 4.0.4 on 2022-08-27 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_beautisiondetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beautisiondetail',
            old_name='b_city',
            new_name='bcity',
        ),
    ]
