# Generated by Django 4.0.4 on 2022-08-28 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0003_coupledetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupledetail',
            old_name='description',
            new_name='descriptions',
        ),
    ]
