# Generated by Django 4.0.4 on 2022-08-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0004_rename_description_coupledetail_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupledetail',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
