# Generated by Django 4.0.4 on 2022-09-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0005_alter_coupledetail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupleguestdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
