# Generated by Django 4.0.4 on 2022-09-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0006_coupleguestdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regdetail',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
