# Generated by Django 4.0.4 on 2022-09-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0007_alter_regdetail_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regdetail',
            name='conformpassword',
            field=models.CharField(max_length=50),
        ),
    ]
